# Generated by Django 4.0.1 on 2022-03-09 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='phone',
            new_name='phone1',
        ),
        migrations.AddField(
            model_name='order',
            name='phone2',
            field=models.IntegerField(default=0),
        ),
    ]
