# Generated by Django 4.0.1 on 2022-03-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_rename_address_order_address1_order_address2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address2',
            field=models.CharField(default='', max_length=111),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone1',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone2',
            field=models.IntegerField(default=''),
        ),
    ]
