# Generated by Django 4.0.1 on 2022-03-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_order_address2_alter_order_phone1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone2',
            field=models.CharField(max_length=13),
        ),
    ]
