# Generated by Django 4.0.1 on 2022-03-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_order_phone2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone1',
            field=models.CharField(default='', max_length=13),
        ),
    ]
